### ISSUE TITLE
How to make two cards with different content?

### ISSUE THREAD

**Issue by o7n** [m-a-k-o/nova-custom-table-card#1]
When I define two cards with different content, I get two cards showing the same content (of the card that was defined last)

Is there any way to get multiple cards by just defining multiple CustomTableCard in the service provider and passing them different arrays?

**Comment by m-a-k-o** [comment]
Hi,

I know about this bug. I'm going to release new version of the package (today/tomorrow) which will solve the problem.

**Comment by m-a-k-o** [comment]
@o7n New version released. Please update to version 1.3. You will be able to use multiple CustomTableCard with different data.
