### ISSUE TITLE
Idea: add a 'show all' link to the bottom of the list

### ISSUE THREAD

**Issue by drsdre** [m-a-k-o/nova-custom-table-card#13]
I would like to have the ability to add a link in the last row of the results that links to the full list of items using a simple link.

**Comment by m-a-k-o** [comment]
Hi @drsdre.

Thank you for your idea. I would be glad if you can make PR with your idea.

**Comment by m-a-k-o** [comment]
Added in following commit https://github.com/m-a-k-o/nova-custom-table-card/commit/5d5e07c5a8c8976be7756c5f0aa7b485f94b2cc6 and version 2.1.0

Thank you @rehmatworks for contribution.
