### ISSUE TITLE
Table data seems to cache when moving between dashboards

### ISSUE THREAD

**Issue by patricktsg** [m-a-k-o/nova-custom-table-card#15]
I have two dashboards, Users Insights and Asset Insights.

On those respective dashboards there are tables called 'Most Active Users' and Most Active Assets'.

If I go to the Users dash first it loads the card table with that user data, but then if I got to the Assets dashboard the table name is correct but it still has the user data in it not the assets.

Is there some default caching going on?

**Comment by m-a-k-o** [comment]
@patricktsg There is no caching.

So you use two different dashboards ?

**Comment by patricktsg** [comment]
> @patricktsg There is no caching.
> 
> So you use two different dashboards ?

Yeah two dashboards and when I go into the first one then into the next the card shows the same data as the first dash I visited until I hard refresh the page. I don't think the route change is triggering the data loading?

**Comment by m-a-k-o** [comment]
@patricktsg Thanks. Can you look at card api response and copy it here ?

**Comment by patricktsg** [comment]
The response data rows are in-fact correct when I change dashboard but the data in the table still shows the previous page table data. Also, some of the styling (fonts) seem to loose the default nova css

**Comment by patricktsg** [comment]
![Screenshot 2020-04-15 at 09 39 38](https://user-images.githubusercontent.com/16956839/79317008-12798180-7efd-11ea-87bc-9c384afda25a.png)
![Screenshot 2020-04-15 at 09 39 18](https://user-images.githubusercontent.com/16956839/79317024-16a59f00-7efd-11ea-8ea6-67ef31aace79.png)

**Comment by m-a-k-o** [comment]
@patricktsg Thans.

Can you send full response from API also with uuid and full rows response?

**Comment by meredyk** [comment]
@m-a-k-o I have the same problem when use more than one dashboard.

**Comment by m-a-k-o** [comment]
@meredyk @patricktsg 
Fixed in following release https://github.com/m-a-k-o/nova-custom-table-card/releases/tag/3.0.0

Please note, refresh has been removed.
