### ISSUE TITLE
More screenshots?

### ISSUE THREAD

**Issue by mikeerickson** [m-a-k-o/nova-custom-table-card#17]
I am curious if you have more screenshots available which shows more columns (and rows) than what is displayed with the basic screenshot you have supplied.

I am most curious to see how it appears with 10 or so columns and 1000+ rows (assuming it does some pagination).

I have not yet installed Nova, and I am trying to see if it will be worth using as an "Admin" interface to our application, or if we are going to need to roll our own interface.

**Comment by m-a-k-o** [comment]
@mikeerickson Hi,

Package does not have pagination. You are free to specify yourself how many rows you want display to a user.

Package only helps you to show data you provide. So logic behind (how many rows, what kind of rows will be show to a user) it is up to you.

If you need more information about Nova contact me at marek@racik.info

and yes nova is worth it 🙂
