### ISSUE TITLE
Idea: Hide the last column when the view is not specified

### ISSUE THREAD

**Issue by meredyk** [m-a-k-o/nova-custom-table-card#18]
Is it possible to hide the last column when the view is not specified?

![Captura de Tela 2020-06-08 às 00 14 00](https://user-images.githubusercontent.com/2585865/83989598-4b423f80-a91d-11ea-8962-dea6f3ecfa59.png)

**Comment by m-a-k-o** [comment]
Thanks to @danielztolnai.
