### ISSUE TITLE
Filters and Actions?

### ISSUE THREAD

**Issue by gearoid-lynch** [m-a-k-o/nova-custom-table-card#21]
Is it possible to add filters to the table ? Also is it possible to add actions to the table?

**Comment by m-a-k-o** [comment]
@lynchy-boop no.

I have in plan v4 with full support for Resource fields, actions, filters and so on, but if you would like enhance current version with actions and filters, please open PR  👍

Thank you 🙂

**Comment by shawngoh87** [comment]
@m-a-k-o 
May I know is there any roadmap/timeline for v4? We are looking into a date range filter as well, so it will be great if we can collab/discuss on this to prevent duplicate effort.
