### ISSUE TITLE
Center header fields

### ISSUE THREAD

**Issue by Bautistaluis** [m-a-k-o/nova-custom-table-card#3]
Hello, I am currently using your package and I would like to know how I can complete the header fields.
I found the solution on the route m-a-k-o / nova-custom-table-card / dist / js / cards.js
But when you update your package and I run composer update, there will be conflicts.
To avoid this, I hope you give me a solution.
@m-a-k-o

**Comment by m-a-k-o** [comment]
Hi. I'm happy that your are using my package. 

I will try to update package asap to provide you needed functionality.

**Comment by m-a-k-o** [comment]
Hi.

I released new version(2.0.0) please check readme and update your package.

You will be able to add classes, ids and refresh the cards.
