### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by meyer59** [m-a-k-o/nova-custom-table-card#30]

**Comment by m-a-k-o** [comment]
Support for Nova 4 should be added soon.

**Comment by MCKLtech** [comment]
+1 for Nova 4 support.

**Comment by Melvintehubijuluw** [comment]
Any updates on the support for nova 4?

**Comment by miki131** [comment]
Any news?

**Comment by m-a-k-o** [comment]
Package version 4 with Nova 4 support released.

Thanks @miki131 for help :)
