### ISSUE TITLE
How get dynamic data

### ISSUE THREAD

**Issue by num3r06** [m-a-k-o/nova-custom-table-card#5]
Hi,
How it is possible retrieve data from database when page it's reloaded?
In the example only static data are represented.
Thx

**Comment by m-a-k-o** [comment]
Hi,

Thank you for opening the issue ;) 

I will update with more examples ASAP.

**Comment by jrmadsen67** [comment]
If you change `_convertToArray()` to protected it will make life a little simpler.

Then people can simply extend CustomTableCard & load `header` &  `data` dynamically, then load only the Card in the NovaServiceProvider

**Comment by num3r06** [comment]
> CustomTableCard

With this method i hacker card source. Maybe it's better a "soft" method.
I try this but doesn't works
thx

**Comment by m-a-k-o** [comment]
You can create your own class which will extend `\Mako\CustomTableCard\CustomTableCard`.

In this separate class you are able to fetch data from models in nice clean way.

```
<?php

namespace App\Nova\Cards;

use App\Models\Order;

class LatestOrders extends \Mako\CustomTableCard\CustomTableCard
{
    public function __construct()
    {
        $header = collect(['Date', 'Order Number', 'Status', 'Price', 'Name']);

        $this->title('Latest Orders');
        $this->refresh(5); // If you need refresh your card data (in seconds)

        // $orders = Order::all();
        // Data from you model
        $orders = collect([
            ['date' => '2018-12-01', 'order_number' => '2018120101', 'status' => 'Ordered', 'price' => '20.55', 'name' => 'John Doe'],
            ['date' => '2018-12-01', 'order_number' => '2018120101', 'status' => 'Ordered', 'price' => '20.55', 'name' => 'John Doe'],
            ['date' => '2018-12-01', 'order_number' => '2018120101', 'status' => 'Ordered', 'price' => '20.55', 'name' => 'John Doe'],
            ['date' => '2018-12-01', 'order_number' => '2018120101', 'status' => 'Ordered', 'price' => '20.55', 'name' => 'John Doe'],
            ['date' => '2018-12-01', 'order_number' => '2018120101', 'status' => 'Ordered', 'price' => '20.55', 'name' => 'John Doe'],
            ['date' => '2018-12-01', 'order_number' => '2018120101', 'status' => 'Ordered', 'price' => '20.55', 'name' => 'John Doe'],
        ]);

        $this->header($header->map(function($value) {
            return new \Mako\CustomTableCard\Table\Cell($value);
        })->toArray());

        $this->data($orders->map(function($order) {
            return new \Mako\CustomTableCard\Table\Row(
                new \Mako\CustomTableCard\Table\Cell($order['date']),
                new \Mako\CustomTableCard\Table\Cell($order['order_number']),
                new \Mako\CustomTableCard\Table\Cell($order['status']),
                new \Mako\CustomTableCard\Table\Cell($order['price']),
                new \Mako\CustomTableCard\Table\Cell($order['name'])
            );
        })->toArray());
    }
}
```
Then register your custom class inside cards  in `NovaServiceProvider.php`
```
    protected function cards()
    {
        return [
            ......
            new \App\Nova\Cards\LatestOrders,
         ];
     }

```

I guess I will make update to simplify inserting data. Maybe allow passing arrays (?) Let' see.

I hope I help you with this example.

If you have more questions. Let me know!

**Comment by simona2017** [comment]
Hi, Thank you so much for providing this example. I had tried to use it by maping it to my sql tables and is not working to pull the data, it just giving me static text. Do you see what I'm doing wrong?

namespace App\Nova\Cards;

use App\Equipment;
use Laravel\Nova\Fields\Number;

class LatestEquipment extends \Mako\CustomTableCard\CustomTableCard
{
    public function __construct()
    {
        $header = collect(['Name', 'Device', 'Equipment Value']);

        $this->title('Equipment');
        $this->refresh(5); // If you need refresh your card data (in seconds)

        $orders = Equipment::all();
        $orders = collect([
          [ 'name' => 'name', 'code	' => 'code	', 'equipment_value' => 'equipment_value'],

        ]);

        $this->header($header->map(function($value) {
            return new \Mako\CustomTableCard\Table\Cell($value);
        })->toArray());

        $this->data($orders->map(function($order) {
            return new \Mako\CustomTableCard\Table\Row(
                new \Mako\CustomTableCard\Table\Cell($order['name']),
                new \Mako\CustomTableCard\Table\Cell($order['code	']),
                new \Mako\CustomTableCard\Table\Cell($order['equipment_value'])
              );
                 })->toArray());
             }
         }

**Comment by jrmadsen67** [comment]
This is not going to work, of course:

    $orders = Equipment::all();
    $orders = collect([
      [ 'name' => 'name', 'code	' => 'code	', 'equipment_value' =>
'equipment_value'],

    ]);

**Comment by simona2017** [comment]
Thank you so much. Is it possible to let me know what would work. I’m just learning. Thanks so much I appreciate the help

**Comment by jrmadsen67** [comment]
you're setting the variable and then resetting it to the static array. you
need to loop over $orders and build the array that way

**Comment by m-a-k-o** [comment]
Closing the issue. Please open new issue if needed.

Thank you.
